"use strict";

(function initSolisUI(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.SolisUI = api;

  if (root?.document) {
    const preferences = api.loadPreferences(root.localStorage, root.navigator?.language);
    api.applyPreferences(root.document, preferences);
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function buildSolisUI() {
  const SUPPORTED_THEMES = ["light", "dark", "system"];
  const SUPPORTED_LANGUAGES = ["zh-CN", "en"];

  const zh = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse 延时摄影工作台",
    "nav.primary": "主导航",
    "nav.workbench": "工作台",
    "nav.hdr": "HDR 合成",
    "nav.history": "归档与日志",
    "nav.logs": "日志",
    "nav.recipes": "色彩配方",
    "nav.settings": "设置",
    "theme.label": "主题",
    "theme.light": "白天",
    "theme.dark": "夜间",
    "theme.system": "跟随系统",
    "language.label": "语言",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "尚未选择素材目录",
    "source.title": "素材",
    "source.help": "选择包含 ARW、JPG 或 JPEG 的目录。",
    "source.summary": "{frames} 帧，{segments} 个分段，拍摄时长 {duration}",
    "source.duration": "{minutes} 分 {seconds} 秒",
    "source.pick": "选择目录",
    "source.rescan": "重新扫描",
    "source.clear": "清除当前项目",
    "source.external_safe": "外部源照片始终保留",
    "segment.title": "分段",
    "segment.count": "{count} 段",
    "segment.empty": "扫描后在此审核分段",
    "segment.unnamed": "未命名分段",
    "segment.focal_unknown": "焦距未知",
    "segment.date_unknown": "日期未知",
    "segment.time_unknown": "时间未知",
    "segment.aperture_unknown": "光圈未知",
    "segment.shutter_unknown": "快门未知",
    "segment.iso_unknown": "ISO 未知",
    "segment.location_unknown": "位置未知",
    "segment.meta_frame_focal": "{count} 帧 · {focal}",
    "segment.meta_date_time": "{date} · {time}",
    "segment.meta_exposure": "{aperture} · {shutter} · {iso}",
    "segment.meta_location": "{location}",
    "segment.list": "分段列表",
    "segment.reorder": "调整分段顺序",
    "segment.move_up": "上移分段",
    "segment.move_down": "下移分段",
    "segment.multi_select": "多选",
    "segment.merge_select": "选择要合并分段",
    "segment.split_frame": "拆分帧",
    "segment.split": "拆分",
    "segment.merge": "合并",
    "segment.current": "当前分段",
    "segment.select": "选择一个分段",
    "segment.none": "未选择",
    "segment.frames": "{count} 帧 · {duration}",
    "segment.frames_only": "{count} 帧",
    "segment.duration": "{seconds} 秒",
    "preview.none": "暂无预览",
    "preview.select": "选择分段后查看代表帧",
    "preview.current": "当前分段预览",
    "preview.histogram": "直方图",
    "preview.histogram_aria": "当前画面 RGB 直方图",
    "preview.alt": "{name}代表帧",
    "preview.representative": "当前代表帧",
    "preview.waiting": "正在等待缩略图",
    "preview.unknown": "未知",
    "preview.focal": "焦距 {value}",
    "preview.aperture": "光圈 {value}",
    "preview.shutter": "快门 {value}",
    "preview.location": "位置 {value}",
    "preview.exposure_bias": "曝光补偿 {value}",
    "exif.open": "查看全部 EXIF",
    "exif.title": "EXIF 全部信息",
    "exif.title_for": "EXIF · {name}",
    "exif.loading": "正在读取原始照片元数据…",
    "exif.count": "共 {count} 个可读标签",
    "exif.group": "分组",
    "exif.tag": "标签",
    "exif.value": "值",
    "exif.empty": "没有可显示的 EXIF 标签",
    "exif.failed": "EXIF 信息读取失败",
    "chart.title": "视频图表",
    "chart.type_label": "图表类型",
    "chart.type.brightness": "亮度趋势",
    "chart.type.gain": "曝光增益",
    "chart.type.change": "帧间变化",
    "chart.legend.brightness": "原始 / 目标",
    "chart.legend.gain": "增益（1.0 = 不调整）",
    "chart.legend.change": "相邻帧亮度差",
    "chart.aria": "视频逐帧分析图表",
    "chart.empty": "分析后显示曲线",
    "recipe.title": "色彩配方",
    "recipe.mode": "配方预设",
    "recipe.natural": "自然",
    "recipe.clear": "通透",
    "recipe.punchy": "色彩强化",
    "recipe.custom": "自定义",
    "recipe.strength": "配方强度",
    "recipe.golden": "霞光增强",
    "recipe.deflicker": "启用去闪",
    "recipe.advanced": "高级参数",
    "recipe.window": "去闪窗口",
    "recipe.gain_limit": "曝光增益上限",
    "recipe.golden_start": "强化起始帧",
    "recipe.golden_end": "强化结束帧",
    "frames.title": "帧检查",
    "frames.multi_select": "多选",
    "frames.none_selected": "未选择帧",
    "frames.selected": "已选择 {count} 帧",
    "frames.selected_range": "已选 {count} 帧：{start}–{end}",
    "frames.empty": "该分段暂无缩略图",
    "frames.select_segment": "选择分段后检查帧",
    "frames.strip": "分段缩略图带",
    "frames.previous": "上一页缩略图",
    "frames.next": "下一页缩略图",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "标记坏帧",
    "frames.unmark_bad": "取消坏帧",
    "frames.send_hdr": "发送到 HDR",
    "frames.set_golden_start": "设为强化起点",
    "frames.set_golden_end": "设为强化终点",
    "frames.bad": "坏帧",
    "frames.index": "第 {index} 帧",
    "frames.shutter": "快门 {value}",
    "frames.luminance": "亮度 {value}",
    "hdr.title": "HDR 合成",
    "hdr.help": "合并同一场景的包围曝光照片，保留高光与阴影细节。",
    "hdr.source": "已选原片",
    "hdr.empty": "在工作台帧检查中多选 2–9 张照片，然后发送到 HDR。",
    "hdr.selection_summary": "{segment} · {count} 张 · 最大间隔 {gap}",
    "hdr.gap_unknown": "时间未知",
    "hdr.preview_empty": "合成后在此显示预览",
    "hdr.preview_caption": "尚未生成 HDR 成果",
    "hdr.preview_selected": "当前显示所选原片；开始合成后将替换为 HDR 成果。",
    "hdr.parameters": "合成参数",
    "hdr.mode": "合成模式",
    "hdr.mode_fusion": "曝光融合",
    "hdr.mode_radiance": "辐射 HDR",
    "hdr.mode_fusion_help": "适合大多数照片，不依赖快门 EXIF，成片自然。",
    "hdr.mode_radiance_help": "根据快门时间恢复辐射信息，再进行色调映射；所有照片必须包含有效快门 EXIF。",
    "hdr.align": "自动对齐",
    "hdr.crop": "裁切对齐边缘",
    "hdr.deghost": "运动抑制",
    "hdr.fusion_parameters": "曝光融合权重",
    "hdr.contrast_weight": "细节对比",
    "hdr.saturation_weight": "色彩权重",
    "hdr.exposure_weight": "曝光权重",
    "hdr.tonemap_parameters": "色调映射",
    "hdr.gamma": "伽马",
    "hdr.intensity": "整体亮度",
    "hdr.light_adapt": "明暗适应",
    "hdr.color_adapt": "色彩适应",
    "hdr.finish_parameters": "成片调整",
    "hdr.post_contrast": "最终对比度",
    "hdr.post_saturation": "最终饱和度",
    "hdr.output_format": "输出格式",
    "hdr.jpeg": "JPEG",
    "hdr.tiff": "16 位 TIFF",
    "hdr.start": "开始合成",
    "hdr.download": "下载成果",
    "hdr.running": "正在合成 HDR",
    "hdr.completed": "HDR 合成完成：{name}",
    "hdr.cancelled": "HDR 合成已取消",
    "hdr.failed": "HDR 合成失败，请查看日志。",
    "export.title": "最终导出",
    "export.help": "渲染、导出、预览和归档仅作用于当前分段。",
    "export.fps": "帧率",
    "export.resolution": "分辨率",
    "export.codec": "编码",
    "export.crf": "CRF",
    "export.source_width": "原图宽度",
    "export.start": "导出视频",
    "export.preview": "预览视频",
    "archive.start": "归档成果",
    "archive.explain": "归档原始照片和最终 MP4",
    "history.title": "归档与日志",
    "history.help": "查看归档成果和当前服务的处理日志。",
    "history.archive_heading": "归档记录",
    "history.refresh": "刷新",
    "history.delete": "删除",
    "history.delete_all": "全部删除",
    "history.delete_confirm": "确定永久删除归档 {timestamp}？该操作会删除其中的原始照片和最终成片，无法撤销。",
    "history.delete_all_confirm": "确定永久删除全部 {count} 条归档？其中的原始照片和最终成片都会被删除，无法撤销。",
    "history.loading": "正在读取历史...",
    "history.empty": "暂无归档",
    "history.legacy": "旧版归档",
    "history.source_unavailable": "源目录记录不可用",
    "history.counts": "{segments} 段 · {originals} 个原始文件",
    "history.file_range": "文件范围：{value}",
    "history.recipe": "配方：{value}",
    "history.focal": "焦距：{value}",
    "history.capture_date": "拍摄日期：{value}",
    "history.capture_time": "拍摄时间：{value}",
    "history.location": "拍摄位置：{value}",
    "history.output": "最终成片",
    "history.missing": "{label}：无",
    "history.record_unavailable": "记录不可用",
    "settings.title": "设置",
    "settings.help": "设置只保存到本机配置。",
    "settings.directories": "目录",
    "settings.workspace": "工作目录",
    "settings.output": "输出目录",
    "settings.archive": "归档目录",
    "settings.pick": "选择",
    "settings.processing": "处理",
    "settings.default_recipe": "默认配方",
    "settings.render_device": "RAW/JPEG 渲染设备",
    "settings.device_auto": "自动（推荐）",
    "settings.gap": "自动分段时间间隔（秒）",
    "settings.log_level": "日志级别",
    "settings.logging": "DEBUG 会记录逐帧进度、处理参数和异常堆栈。",
    "settings.preview": "预览",
    "settings.preview_fps": "预览帧率",
    "settings.preview_width": "预览宽度",
    "settings.export": "导出",
    "settings.save": "保存设置",
    "settings.saved": "已保存",
    "settings.saved_restart": "已保存，重启程序后生效",
    "logs.title": "任务日志",
    "logs.help": "显示当前服务运行期间的任务记录，命令行窗口会同步输出。",
    "logs.clear": "清除历史日志",
    "presets.title": "色彩配方",
    "presets.help": "管理实际参与渲染的饱和度、对比度和明暗枢轴参数。",
    "presets.list": "色彩配方列表",
    "presets.editor": "配方参数",
    "presets.new": "新建配方",
    "presets.new_badge": "新配方",
    "presets.name": "名称",
    "presets.saturation": "饱和度",
    "presets.contrast": "对比度",
    "presets.pivot": "明暗枢轴",
    "presets.builtin": "内置",
    "presets.user": "自定义",
    "presets.unnamed": "未命名配方",
    "presets.save": "保存预设",
    "presets.delete": "删除预设",
    "presets.saved": "配方已保存",
    "presets.deleted": "配方已删除",
    "presets.delete_confirm": "确认删除配方“{name}”？",
    "task.bar": "任务状态栏",
    "task.current_panel": "当前分段任务",
    "task.start": "开始处理",
    "task.start_current": "渲染",
    "task.cancel": "取消",
    "task.progress": "任务进度",
    "task.waiting": "等待任务",
    "task.logs": "任务日志",
    "task.no_logs": "暂无日志",
    "status.idle": "空闲",
    "status.pending": "待处理",
    "status.analyzed": "已分析",
    "status.rendered": "已渲染",
    "status.queued": "排队中",
    "status.running": "处理中",
    "status.completed": "已完成",
    "status.exported": "已导出",
    "status.archived": "已归档",
    "status.failed": "失败",
    "status.cancelling": "正在取消",
    "status.cancelled": "已取消",
    "status.interrupted": "已中断",
    "status.unknown": "未知",
    "dialog.archive.title": "确认归档当前分段",
    "dialog.archive.body": "将归档当前分段：{name}\n保存原始照片（保留 ARW/JPG）和最终 MP4；不保存处理后 JPG 或预览视频。",
    "dialog.archive.confirm": "确认归档",
    "dialog.archive_progress.title": "正在归档成果",
    "dialog.archive_progress.preparing": "正在准备当前分段的原始照片和最终 MP4。",
    "dialog.archive_progress.waiting": "正在复制并校验原始照片，请等待。",
    "dialog.archive_progress.cancelling": "正在取消归档",
    "dialog.archive_progress.cancelling_waiting": "正在停止归档，请等待。",
    "dialog.archive_progress.cancel": "取消归档",
    "dialog.archive_progress.cancelled": "成果归档已取消",
    "dialog.archive_progress.cancelled_body": "未完成的临时归档已删除，正式归档目录未发布。",
    "dialog.archive_progress.failed": "成果归档失败",
    "dialog.archive_progress.aria": "成果归档处理中",
    "dialog.scan_progress.title": "正在扫描素材",
    "dialog.scan_progress.preparing": "正在读取素材目录，请稍候。",
    "dialog.scan_progress.cancelling": "正在取消扫描",
    "dialog.scan_progress.cancelling_body": "正在停止素材扫描，请等待。",
    "dialog.scan_progress.cancel": "取消扫描",
    "dialog.scan_progress.cancelled": "素材扫描已取消",
    "dialog.scan_progress.cancelled_body": "扫描任务已停止，未完成的扫描结果不会保存。",
    "dialog.scan_progress.failed": "素材扫描失败",
    "dialog.scan_progress.completed": "素材扫描完成",
    "dialog.scan_progress.completed_body": "已完成扫描并生成 {count} 个分段。",
    "dialog.scan_progress.aria": "素材扫描进度",
    "dialog.export_progress.title": "正在导出视频",
    "dialog.export_progress.preparing": "正在准备当前分段，请稍候。",
    "dialog.export_progress.waiting": "视频正在导出，请等待。",
    "dialog.export_progress.stats_preparing": "正在读取帧信息。",
    "dialog.export_progress.stats": "{done} / {total} 帧 · {encoder} · {fps} 帧/秒 · 剩余 {eta}",
    "dialog.export_progress.eta_calculating": "计算中",
    "dialog.export_progress.eta_seconds": "{seconds} 秒",
    "dialog.export_progress.eta_minutes": "{minutes} 分 {seconds} 秒",
    "dialog.export_progress.cancelling": "正在取消导出",
    "dialog.export_progress.cancelling_waiting": "正在停止导出，请等待。",
    "dialog.export_progress.cancel": "取消导出",
    "dialog.export_progress.cancelled": "视频导出已取消",
    "dialog.export_progress.cancelled_body": "未完成的导出任务已停止。",
    "dialog.export_progress.failed": "视频导出失败",
    "dialog.export_progress.h264_oversize": "当前分段约为 {width}×{height}。原图 H.264 超过 NVIDIA 硬件编码限制，会退回极慢的 CPU 编码。请选择“原图宽度 + H.265”，或“4K + H.264”。",
    "dialog.export_progress.aria": "视频导出处理中",
    "dialog.export_done.title": "视频导出完成",
    "dialog.export_done.body": "导出目录：{path}\n文件：{files}",
    "dialog.archive_done.title": "成果归档完成",
    "dialog.archive_done.body": "归档目录：{path}\n原始照片和最终 MP4 已完成复制及校验。",
    "dialog.result.history": "查看历史归档",
    "dialog.result.ok": "确定",
    "dialog.clear.title": "清除当前项目",
    "dialog.clear.warning": "以下目录中的当前项目数据将被永久删除：",
    "dialog.clear.workspace": "当前项目工作区",
    "dialog.clear.output": "输出目录（包括尚未归档的视频）",
    "dialog.clear.preserved": "源照片不会删除。归档目录中的成果保持不变：",
    "dialog.clear.irreversible": "此操作不会自动归档，且无法撤销。",
    "dialog.clear.confirm": "确认清除",
    "dialog.cancel": "取消",
    "dialog.close": "关闭",
    "browser.title": "选择素材目录",
    "browser.breadcrumb": "素材目录路径",
    "browser.root": "根目录",
    "browser.empty": "当前目录没有子目录",
    "browser.choose": "选择当前目录",
    "error.dismiss": "关闭错误提示",
    "error.invalid_media_path": "素材目录无效或超出允许范围。",
    "error.native_picker_unavailable": "当前运行模式不支持本机目录选择器。",
    "error.runtime_unavailable": "运行目录不可用，请检查挂载和权限。",
    "error.task_busy": "已有任务正在运行。",
    "error.invalid_color_preset": "色彩配方参数无效。",
    "error.preset_builtin": "内置色彩配方不能删除。",
    "error.preset_in_use": "该色彩配方正在使用，不能删除。",
    "error.preset_not_found": "色彩配方不存在。",
    "error.invalid_hdr": "请选择同一分段中的 2–9 张不同照片。",
    "error.hdr_exposure_missing": "辐射 HDR 需要每张照片都包含有效快门时间。",
    "error.not_found": "请求的资源不存在。",
    "error.internal_error": "服务器处理请求时失败。",
    "error.unknown": "操作失败。"
  };

  const en = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse Workbench",
    "nav.primary": "Primary navigation",
    "nav.workbench": "Workbench",
    "nav.hdr": "HDR merge",
    "nav.history": "Archives & Logs",
    "nav.logs": "Logs",
    "nav.recipes": "Color recipes",
    "nav.settings": "Settings",
    "theme.label": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "language.label": "Language",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "No source folder selected",
    "source.title": "Source",
    "source.help": "Choose a folder containing ARW, JPG, or JPEG files.",
    "source.summary": "{frames} frames, {segments} segments, capture duration {duration}",
    "source.duration": "{minutes} min {seconds} sec",
    "source.pick": "Choose folder",
    "source.rescan": "Rescan",
    "source.clear": "Clear project",
    "source.external_safe": "External source photos are always preserved",
    "segment.title": "Segments",
    "segment.count": "{count} segments",
    "segment.empty": "Scan a source to review its segments here",
    "segment.unnamed": "Unnamed segment",
    "segment.focal_unknown": "Focal length unknown",
    "segment.date_unknown": "Date unknown",
    "segment.time_unknown": "Time unknown",
    "segment.aperture_unknown": "Aperture unknown",
    "segment.shutter_unknown": "Shutter unknown",
    "segment.iso_unknown": "ISO unknown",
    "segment.location_unknown": "Location unknown",
    "segment.meta_frame_focal": "{count} frames · {focal}",
    "segment.meta_date_time": "{date} · {time}",
    "segment.meta_exposure": "{aperture} · {shutter} · {iso}",
    "segment.meta_location": "{location}",
    "segment.list": "Segment list",
    "segment.reorder": "Reorder segments",
    "segment.move_up": "Move segment up",
    "segment.move_down": "Move segment down",
    "segment.multi_select": "Multi-select",
    "segment.merge_select": "Select segments to merge",
    "segment.split_frame": "Split frame",
    "segment.split": "Split",
    "segment.merge": "Merge",
    "segment.current": "Current segment",
    "segment.select": "Select a segment",
    "segment.none": "Not selected",
    "segment.frames": "{count} frames · {duration}",
    "segment.frames_only": "{count} frames",
    "segment.duration": "{seconds} sec",
    "preview.none": "No preview",
    "preview.select": "Select a segment to view its representative frame",
    "preview.current": "Current segment preview",
    "preview.histogram": "Histogram",
    "preview.histogram_aria": "Current image RGB histogram",
    "preview.alt": "Representative frame for {name}",
    "preview.representative": "Current representative frame",
    "preview.waiting": "Waiting for thumbnails",
    "preview.unknown": "Unknown",
    "preview.focal": "Focal length {value}",
    "preview.aperture": "Aperture {value}",
    "preview.shutter": "Shutter {value}",
    "preview.location": "Location {value}",
    "preview.exposure_bias": "Exposure compensation {value}",
    "exif.open": "View all EXIF",
    "exif.title": "All EXIF metadata",
    "exif.title_for": "EXIF · {name}",
    "exif.loading": "Reading metadata from the source photo…",
    "exif.count": "{count} readable tags",
    "exif.group": "Group",
    "exif.tag": "Tag",
    "exif.value": "Value",
    "exif.empty": "No EXIF tags to display",
    "exif.failed": "Unable to read EXIF metadata",
    "chart.title": "Video charts",
    "chart.type_label": "Chart type",
    "chart.type.brightness": "Brightness trend",
    "chart.type.gain": "Exposure gain",
    "chart.type.change": "Frame change",
    "chart.legend.brightness": "Original / Target",
    "chart.legend.gain": "Gain (1.0 = unchanged)",
    "chart.legend.change": "Brightness difference between adjacent frames",
    "chart.aria": "Per-frame video analysis chart",
    "chart.empty": "Run analysis to display curves",
    "recipe.title": "Color recipe",
    "recipe.mode": "Recipe preset",
    "recipe.natural": "Natural",
    "recipe.clear": "Clear",
    "recipe.punchy": "Color boost",
    "recipe.custom": "Custom",
    "recipe.strength": "Recipe strength",
    "recipe.golden": "Alpenglow boost",
    "recipe.deflicker": "Enable deflicker",
    "recipe.advanced": "Advanced parameters",
    "recipe.window": "Deflicker window",
    "recipe.gain_limit": "Exposure gain limit",
    "recipe.golden_start": "Boost start frame",
    "recipe.golden_end": "Boost end frame",
    "frames.title": "Frame review",
    "frames.multi_select": "Multi-select",
    "frames.none_selected": "No frames selected",
    "frames.selected": "{count} frames selected",
    "frames.selected_range": "{count} frames selected: {start}–{end}",
    "frames.empty": "No thumbnails for this segment",
    "frames.select_segment": "Select a segment to review frames",
    "frames.strip": "Segment thumbnail strip",
    "frames.previous": "Previous thumbnail page",
    "frames.next": "Next thumbnail page",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "Mark bad frame",
    "frames.unmark_bad": "Unmark bad frame",
    "frames.send_hdr": "Send to HDR",
    "frames.set_golden_start": "Set boost start",
    "frames.set_golden_end": "Set boost end",
    "frames.bad": "Bad frame",
    "frames.index": "Frame {index}",
    "frames.shutter": "Shutter {value}",
    "frames.luminance": "Brightness {value}",
    "hdr.title": "HDR merge",
    "hdr.help": "Merge bracketed photos of the same scene while retaining highlight and shadow detail.",
    "hdr.source": "Selected originals",
    "hdr.empty": "Select 2–9 photos in Workbench frame review, then send them to HDR.",
    "hdr.selection_summary": "{segment} · {count} photos · max gap {gap}",
    "hdr.gap_unknown": "time unknown",
    "hdr.preview_empty": "The merged preview appears here",
    "hdr.preview_caption": "No HDR result yet",
    "hdr.preview_selected": "Showing a selected original; the HDR result replaces it after merging.",
    "hdr.parameters": "Merge parameters",
    "hdr.mode": "Merge mode",
    "hdr.mode_fusion": "Exposure fusion",
    "hdr.mode_radiance": "Radiance HDR",
    "hdr.mode_fusion_help": "Best for most photos. It does not require shutter EXIF and produces a natural result.",
    "hdr.mode_radiance_help": "Recovers radiance from shutter times, then tone maps it. Every photo must have valid shutter EXIF.",
    "hdr.align": "Auto align",
    "hdr.crop": "Crop alignment edges",
    "hdr.deghost": "Motion suppression",
    "hdr.fusion_parameters": "Exposure-fusion weights",
    "hdr.contrast_weight": "Detail contrast",
    "hdr.saturation_weight": "Color weight",
    "hdr.exposure_weight": "Exposure weight",
    "hdr.tonemap_parameters": "Tone mapping",
    "hdr.gamma": "Gamma",
    "hdr.intensity": "Overall brightness",
    "hdr.light_adapt": "Light adaptation",
    "hdr.color_adapt": "Color adaptation",
    "hdr.finish_parameters": "Finishing",
    "hdr.post_contrast": "Final contrast",
    "hdr.post_saturation": "Final saturation",
    "hdr.output_format": "Output format",
    "hdr.jpeg": "JPEG",
    "hdr.tiff": "16-bit TIFF",
    "hdr.start": "Merge HDR",
    "hdr.download": "Download result",
    "hdr.running": "Merging HDR",
    "hdr.completed": "HDR merge completed: {name}",
    "hdr.cancelled": "HDR merge cancelled",
    "hdr.failed": "HDR merge failed. Check the logs.",
    "export.title": "Final export",
    "export.help": "Render, export, preview, and archive apply only to the current segment.",
    "export.fps": "Frame rate",
    "export.resolution": "Resolution",
    "export.codec": "Codec",
    "export.crf": "CRF",
    "export.source_width": "Source width",
    "export.start": "Export video",
    "export.preview": "Preview video",
    "archive.start": "Archive results",
    "archive.explain": "Archive original photos and the final MP4",
    "history.title": "Archives & Logs",
    "history.help": "Review archived results and processing logs from the current service.",
    "history.archive_heading": "Archive records",
    "history.refresh": "Refresh",
    "history.delete": "Delete",
    "history.delete_all": "Delete all",
    "history.delete_confirm": "Permanently delete archive {timestamp}? Its original photos and final render will be deleted and cannot be recovered.",
    "history.delete_all_confirm": "Permanently delete all {count} archives? Their original photos and final renders will be deleted and cannot be recovered.",
    "history.loading": "Loading history...",
    "history.empty": "No archives",
    "history.legacy": "Legacy archive",
    "history.source_unavailable": "Source folder record unavailable",
    "history.counts": "{segments} segments · {originals} original files",
    "history.file_range": "File range: {value}",
    "history.recipe": "Recipe: {value}",
    "history.focal": "Focal length: {value}",
    "history.capture_date": "Capture date: {value}",
    "history.capture_time": "Capture time: {value}",
    "history.location": "Capture location: {value}",
    "history.output": "Final render",
    "history.missing": "{label}: none",
    "history.record_unavailable": "Record unavailable",
    "settings.title": "Settings",
    "settings.help": "Settings are saved only to local configuration.",
    "settings.directories": "Directories",
    "settings.workspace": "Workspace directory",
    "settings.output": "Output directory",
    "settings.archive": "Archive directory",
    "settings.pick": "Choose",
    "settings.processing": "Processing",
    "settings.default_recipe": "Default recipe",
    "settings.render_device": "RAW/JPEG render device",
    "settings.device_auto": "Auto (recommended)",
    "settings.gap": "Automatic segment gap (seconds)",
    "settings.log_level": "Log level",
    "settings.logging": "DEBUG records per-frame progress, processing parameters, and exception tracebacks.",
    "settings.preview": "Preview",
    "settings.preview_fps": "Preview frame rate",
    "settings.preview_width": "Preview width",
    "settings.export": "Export",
    "settings.save": "Save settings",
    "settings.saved": "Saved",
    "settings.saved_restart": "Saved; restart the application to apply",
    "logs.title": "Task logs",
    "logs.help": "Task history for this service session. The command window shows the same events.",
    "logs.clear": "Clear log history",
    "presets.title": "Color recipes",
    "presets.help": "Manage the saturation, contrast, and tonal pivot used during rendering.",
    "presets.list": "Color recipe list",
    "presets.editor": "Recipe parameters",
    "presets.new": "New recipe",
    "presets.new_badge": "New recipe",
    "presets.name": "Name",
    "presets.saturation": "Saturation",
    "presets.contrast": "Contrast",
    "presets.pivot": "Tonal pivot",
    "presets.builtin": "Built in",
    "presets.user": "Custom",
    "presets.unnamed": "Untitled recipe",
    "presets.save": "Save preset",
    "presets.delete": "Delete preset",
    "presets.saved": "Recipe saved",
    "presets.deleted": "Recipe deleted",
    "presets.delete_confirm": "Delete recipe “{name}”?",
    "task.bar": "Task status bar",
    "task.current_panel": "Current segment task",
    "task.start": "Start processing",
    "task.start_current": "Render",
    "task.cancel": "Cancel",
    "task.progress": "Task progress",
    "task.waiting": "Waiting for a task",
    "task.logs": "Task log",
    "task.no_logs": "No log entries",
    "status.idle": "Idle",
    "status.pending": "Pending",
    "status.analyzed": "Analyzed",
    "status.rendered": "Rendered",
    "status.queued": "Queued",
    "status.running": "Processing",
    "status.completed": "Completed",
    "status.exported": "Exported",
    "status.archived": "Archived",
    "status.failed": "Failed",
    "status.cancelling": "Cancelling",
    "status.cancelled": "Cancelled",
    "status.interrupted": "Interrupted",
    "status.unknown": "Unknown",
    "dialog.archive.title": "Archive current segment",
    "dialog.archive.body": "Archive current segment: {name}\nOriginal photos (ARW/JPG) and the final MP4 are saved. Processed JPEGs and preview videos are not saved.",
    "dialog.archive.confirm": "Archive",
    "dialog.archive_progress.title": "Archiving results",
    "dialog.archive_progress.preparing": "Preparing the original photos and final MP4 for this segment.",
    "dialog.archive_progress.waiting": "Copying and verifying original photos. Please wait.",
    "dialog.archive_progress.cancelling": "Cancelling archive",
    "dialog.archive_progress.cancelling_waiting": "Stopping the archive. Please wait.",
    "dialog.archive_progress.cancel": "Cancel archive",
    "dialog.archive_progress.cancelled": "Archive cancelled",
    "dialog.archive_progress.cancelled_body": "The incomplete temporary archive was removed and no final archive was published.",
    "dialog.archive_progress.failed": "Archive failed",
    "dialog.archive_progress.aria": "Archive in progress",
    "dialog.scan_progress.title": "Scanning source",
    "dialog.scan_progress.preparing": "Reading the source folder. Please wait.",
    "dialog.scan_progress.cancelling": "Cancelling scan",
    "dialog.scan_progress.cancelling_body": "Stopping the source scan. Please wait.",
    "dialog.scan_progress.cancel": "Cancel scan",
    "dialog.scan_progress.cancelled": "Source scan cancelled",
    "dialog.scan_progress.cancelled_body": "The scan stopped and incomplete results were not saved.",
    "dialog.scan_progress.failed": "Source scan failed",
    "dialog.scan_progress.completed": "Source scan complete",
    "dialog.scan_progress.completed_body": "Scan complete with {count} segments.",
    "dialog.scan_progress.aria": "Source scan progress",
    "dialog.export_progress.title": "Exporting video",
    "dialog.export_progress.preparing": "Preparing the current segment.",
    "dialog.export_progress.waiting": "Exporting video. Please wait.",
    "dialog.export_progress.stats_preparing": "Reading frame information.",
    "dialog.export_progress.stats": "{done} / {total} frames · {encoder} · {fps} fps · {eta} remaining",
    "dialog.export_progress.eta_calculating": "calculating",
    "dialog.export_progress.eta_seconds": "{seconds}s",
    "dialog.export_progress.eta_minutes": "{minutes}m {seconds}s",
    "dialog.export_progress.cancelling": "Cancelling export",
    "dialog.export_progress.cancelling_waiting": "Stopping the export. Please wait.",
    "dialog.export_progress.cancel": "Cancel export",
    "dialog.export_progress.cancelled": "Video export cancelled",
    "dialog.export_progress.cancelled_body": "The unfinished export task has stopped.",
    "dialog.export_progress.failed": "Video export failed",
    "dialog.export_progress.h264_oversize": "This segment is approximately {width}×{height}. Source-resolution H.264 exceeds NVIDIA hardware limits and would fall back to very slow CPU encoding. Choose Source width + H.265, or 4K + H.264.",
    "dialog.export_progress.aria": "Video export in progress",
    "dialog.export_done.title": "Video export complete",
    "dialog.export_done.body": "Output directory: {path}\nFiles: {files}",
    "dialog.archive_done.title": "Archive complete",
    "dialog.archive_done.body": "Archive directory: {path}\nThe original photos and final MP4 were copied and verified.",
    "dialog.result.history": "View archive history",
    "dialog.result.ok": "OK",
    "dialog.clear.title": "Clear current project",
    "dialog.clear.warning": "Current project data in these directories will be permanently deleted:",
    "dialog.clear.workspace": "Current project workspace",
    "dialog.clear.output": "Output directory (including videos not yet archived)",
    "dialog.clear.preserved": "Source photos will not be deleted. Files in the archive directory remain unchanged:",
    "dialog.clear.irreversible": "This action does not create an archive and cannot be undone.",
    "dialog.clear.confirm": "Clear project",
    "dialog.cancel": "Cancel",
    "dialog.close": "Close",
    "browser.title": "Choose source directory",
    "browser.breadcrumb": "Source directory path",
    "browser.root": "Root",
    "browser.empty": "This directory has no subdirectories",
    "browser.choose": "Choose current directory",
    "error.dismiss": "Dismiss error",
    "error.invalid_media_path": "The source directory is invalid or outside the allowed location.",
    "error.native_picker_unavailable": "The native directory picker is unavailable in this runtime mode.",
    "error.runtime_unavailable": "Runtime directories are unavailable. Check mounts and permissions.",
    "error.task_busy": "Another task is already running.",
    "error.invalid_color_preset": "The color recipe parameters are invalid.",
    "error.preset_builtin": "Built-in color recipes cannot be deleted.",
    "error.preset_in_use": "This color recipe is in use and cannot be deleted.",
    "error.preset_not_found": "The color recipe does not exist.",
    "error.invalid_hdr": "Select 2–9 different photos from the same segment.",
    "error.hdr_exposure_missing": "Radiance HDR requires a valid shutter time for every photo.",
    "error.not_found": "The requested resource does not exist.",
    "error.internal_error": "The server could not complete the request.",
    "error.unknown": "The operation failed."
  };

  const TRANSLATIONS = { "zh-CN": zh, en };

  function normalizeTheme(value) {
    return SUPPORTED_THEMES.includes(value) ? value : "system";
  }

  function normalizeLanguage(value, browserLanguage = "en") {
    if (SUPPORTED_LANGUAGES.includes(value)) return value;
    return String(browserLanguage).toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  }

  function t(language, key, params = {}) {
    const template = TRANSLATIONS[language]?.[key] ?? zh[key];
    if (template === undefined) {
      if (typeof console !== "undefined") console.warn(`Missing translation: ${key}`);
      return key;
    }
    return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
  }

  function loadPreferences(storage, browserLanguage) {
    return {
      theme: normalizeTheme(storage?.getItem("solis.theme")),
      language: normalizeLanguage(storage?.getItem("solis.language"), browserLanguage),
    };
  }

  function applyPreferences(documentRef, preferences) {
    documentRef.documentElement.dataset.theme = normalizeTheme(preferences.theme);
    documentRef.documentElement.lang = normalizeLanguage(preferences.language, preferences.language);
  }

  return {
    SUPPORTED_THEMES,
    SUPPORTED_LANGUAGES,
    TRANSLATIONS,
    normalizeTheme,
    normalizeLanguage,
    t,
    loadPreferences,
    applyPreferences,
  };
});
