"use strict";

(function initSolisUI(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.SolisUI = api;

  if (root?.document) {
    const preferences = api.loadPreferences(root.localStorage, root.navigator?.language);
    api.applyPreferences(root.document, preferences);
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function buildSolisUI() {
  const SUPPORTED_THEMES = ["light", "dark", "system"];
  const SUPPORTED_LANGUAGES = ["zh-CN", "en"];

  const zh = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse 延时摄影工作台",
    "nav.primary": "主导航",
    "nav.workbench": "工作台",
    "nav.history": "历史",
    "nav.settings": "设置",
    "theme.label": "主题",
    "theme.light": "白天",
    "theme.dark": "夜间",
    "theme.system": "跟随系统",
    "language.label": "语言",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "尚未选择素材目录",
    "source.title": "素材",
    "source.help": "选择包含 ARW、JPG 或 JPEG 的目录。",
    "source.summary": "{frames} 帧，{segments} 个分段，拍摄时长 {duration}",
    "source.duration": "{minutes} 分 {seconds} 秒",
    "source.pick": "选择目录",
    "source.scan": "扫描素材",
    "source.clear": "清除当前项目",
    "source.external_safe": "外部源照片始终保留",
    "segment.title": "分段",
    "segment.count": "{count} 段",
    "segment.empty": "扫描后在此审核分段",
    "segment.unnamed": "未命名分段",
    "segment.focal_unknown": "焦距未知",
    "segment.time_unknown": "时间未知",
    "segment.meta": "{count} 帧 · {focal} · {time}",
    "segment.list": "分段列表",
    "segment.reorder": "调整分段顺序",
    "segment.move_up": "上移分段",
    "segment.move_down": "下移分段",
    "segment.split_frame": "拆分帧",
    "segment.split": "拆分",
    "segment.merge": "合并下一段",
    "segment.current": "当前分段",
    "segment.select": "选择一个分段",
    "segment.none": "未选择",
    "segment.frames": "{count} 帧 · {duration}",
    "segment.frames_only": "{count} 帧",
    "segment.duration": "{seconds} 秒",
    "preview.none": "暂无预览",
    "preview.select": "选择分段后查看代表帧",
    "preview.current": "当前分段预览",
    "preview.alt": "{name}代表帧",
    "preview.representative": "当前代表帧",
    "preview.waiting": "正在等待缩略图",
    "chart.title": "亮度曲线",
    "chart.legend": "原始 / 目标 / 增益",
    "chart.aria": "亮度、目标亮度和增益曲线",
    "chart.empty": "分析后显示曲线",
    "recipe.title": "处理配方",
    "recipe.mode": "处理模式",
    "recipe.natural": "自然",
    "recipe.clear": "通透",
    "recipe.punchy": "色彩强化",
    "recipe.custom": "自定义",
    "recipe.strength": "配方强度",
    "recipe.golden": "日照金山强度",
    "recipe.deflicker": "启用去闪",
    "recipe.advanced": "高级参数",
    "recipe.window": "去闪窗口",
    "recipe.gain_limit": "曝光增益上限",
    "recipe.golden_start": "强化起始帧",
    "recipe.golden_end": "强化结束帧",
    "frames.title": "帧检查",
    "frames.none_selected": "未选择帧",
    "frames.selected": "已选择 {count} 帧",
    "frames.selected_range": "已选 {count} 帧：{start}–{end}",
    "frames.empty": "该分段暂无缩略图",
    "frames.select_segment": "选择分段后检查帧",
    "frames.strip": "分段缩略图带",
    "frames.previous": "上一页缩略图",
    "frames.next": "下一页缩略图",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "标记坏帧",
    "frames.unmark_bad": "取消坏帧",
    "frames.set_golden_start": "设为强化起点",
    "frames.set_golden_end": "设为强化终点",
    "frames.bad": "坏帧",
    "frames.index": "第 {index} 帧",
    "frames.shutter": "快门 {value}",
    "frames.luminance": "亮度 {value}",
    "export.title": "最终导出",
    "export.help": "逐段生成最终视频；预览与最终成片分开保存。",
    "export.fps": "帧率",
    "export.resolution": "分辨率",
    "export.codec": "编码",
    "export.crf": "CRF",
    "export.source_width": "原图宽度",
    "export.start": "导出视频",
    "archive.start": "归档成果",
    "history.title": "历史归档",
    "history.help": "预览视频与最终成片分别列出。",
    "history.refresh": "刷新",
    "history.loading": "正在读取历史...",
    "history.empty": "暂无归档",
    "history.legacy": "旧版归档",
    "history.source_unavailable": "源目录记录不可用",
    "history.counts": "{segments} 段 · {jpegs} 张 JPEG",
    "history.recipe": "配方：{value}",
    "history.preview": "预览",
    "history.output": "最终成片",
    "history.missing": "{label}：无",
    "history.record_unavailable": "记录不可用",
    "settings.title": "设置",
    "settings.help": "设置只保存到本机配置。",
    "settings.directories": "目录",
    "settings.workspace": "工作目录",
    "settings.output": "输出目录",
    "settings.archive": "归档目录",
    "settings.pick": "选择",
    "settings.processing": "处理",
    "settings.default_recipe": "默认配方",
    "settings.gap": "自动分段时间间隔（秒）",
    "settings.preview": "预览",
    "settings.preview_fps": "预览帧率",
    "settings.preview_width": "预览宽度",
    "settings.export": "导出",
    "settings.save": "保存设置",
    "settings.saved": "已保存",
    "settings.saved_restart": "已保存，重启程序后生效",
    "task.bar": "任务状态栏",
    "task.start": "开始处理",
    "task.retry_stage": "重跑阶段",
    "task.retry_render": "重新渲染",
    "task.retry_analyze": "重新分析并渲染",
    "task.retry": "重跑",
    "task.cancel": "取消",
    "task.progress": "任务进度",
    "task.waiting": "等待任务",
    "task.logs": "任务日志",
    "task.no_logs": "暂无日志",
    "status.idle": "空闲",
    "status.pending": "待处理",
    "status.analyzed": "已分析",
    "status.rendered": "已渲染",
    "status.queued": "排队中",
    "status.running": "处理中",
    "status.completed": "已完成",
    "status.failed": "失败",
    "status.cancelling": "正在取消",
    "status.cancelled": "已取消",
    "status.interrupted": "已中断",
    "status.unknown": "未知",
    "dialog.archive.title": "确认归档",
    "dialog.archive.body": "归档会校验并保存当前 JPEG、预览视频和最终成片，随后清理工作目录。外部源照片始终保留。",
    "dialog.archive.confirm": "确认归档",
    "dialog.clear.title": "清除当前项目",
    "dialog.clear.body": "这会清除当前工作目录中的项目状态和处理结果，不会删除外部源照片。",
    "dialog.clear.confirm": "确认清除",
    "dialog.cancel": "取消",
    "error.dismiss": "关闭错误提示",
    "error.invalid_media_path": "素材目录无效或超出允许范围。",
    "error.native_picker_unavailable": "当前运行模式不支持本机目录选择器。",
    "error.runtime_unavailable": "运行目录不可用，请检查挂载和权限。",
    "error.task_busy": "已有任务正在运行。",
    "error.not_found": "请求的资源不存在。",
    "error.internal_error": "服务器处理请求时失败。",
    "error.unknown": "操作失败。"
  };

  const en = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse Workbench",
    "nav.primary": "Primary navigation",
    "nav.workbench": "Workbench",
    "nav.history": "History",
    "nav.settings": "Settings",
    "theme.label": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "language.label": "Language",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "No source folder selected",
    "source.title": "Source",
    "source.help": "Choose a folder containing ARW, JPG, or JPEG files.",
    "source.summary": "{frames} frames, {segments} segments, capture duration {duration}",
    "source.duration": "{minutes} min {seconds} sec",
    "source.pick": "Choose folder",
    "source.scan": "Scan source",
    "source.clear": "Clear project",
    "source.external_safe": "External source photos are always preserved",
    "segment.title": "Segments",
    "segment.count": "{count} segments",
    "segment.empty": "Scan a source to review its segments here",
    "segment.unnamed": "Unnamed segment",
    "segment.focal_unknown": "Focal length unknown",
    "segment.time_unknown": "Time unknown",
    "segment.meta": "{count} frames · {focal} · {time}",
    "segment.list": "Segment list",
    "segment.reorder": "Reorder segments",
    "segment.move_up": "Move segment up",
    "segment.move_down": "Move segment down",
    "segment.split_frame": "Split frame",
    "segment.split": "Split",
    "segment.merge": "Merge next",
    "segment.current": "Current segment",
    "segment.select": "Select a segment",
    "segment.none": "Not selected",
    "segment.frames": "{count} frames · {duration}",
    "segment.frames_only": "{count} frames",
    "segment.duration": "{seconds} sec",
    "preview.none": "No preview",
    "preview.select": "Select a segment to view its representative frame",
    "preview.current": "Current segment preview",
    "preview.alt": "Representative frame for {name}",
    "preview.representative": "Current representative frame",
    "preview.waiting": "Waiting for thumbnails",
    "chart.title": "Brightness curve",
    "chart.legend": "Original / Target / Gain",
    "chart.aria": "Brightness, target brightness, and gain curves",
    "chart.empty": "Run analysis to display curves",
    "recipe.title": "Processing recipe",
    "recipe.mode": "Processing mode",
    "recipe.natural": "Natural",
    "recipe.clear": "Clear",
    "recipe.punchy": "Color boost",
    "recipe.custom": "Custom",
    "recipe.strength": "Recipe strength",
    "recipe.golden": "Golden mountain strength",
    "recipe.deflicker": "Enable deflicker",
    "recipe.advanced": "Advanced parameters",
    "recipe.window": "Deflicker window",
    "recipe.gain_limit": "Exposure gain limit",
    "recipe.golden_start": "Boost start frame",
    "recipe.golden_end": "Boost end frame",
    "frames.title": "Frame review",
    "frames.none_selected": "No frames selected",
    "frames.selected": "{count} frames selected",
    "frames.selected_range": "{count} frames selected: {start}–{end}",
    "frames.empty": "No thumbnails for this segment",
    "frames.select_segment": "Select a segment to review frames",
    "frames.strip": "Segment thumbnail strip",
    "frames.previous": "Previous thumbnail page",
    "frames.next": "Next thumbnail page",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "Mark bad frame",
    "frames.unmark_bad": "Unmark bad frame",
    "frames.set_golden_start": "Set boost start",
    "frames.set_golden_end": "Set boost end",
    "frames.bad": "Bad frame",
    "frames.index": "Frame {index}",
    "frames.shutter": "Shutter {value}",
    "frames.luminance": "Brightness {value}",
    "export.title": "Final export",
    "export.help": "Generate one final video per segment; previews and final renders are stored separately.",
    "export.fps": "Frame rate",
    "export.resolution": "Resolution",
    "export.codec": "Codec",
    "export.crf": "CRF",
    "export.source_width": "Source width",
    "export.start": "Export video",
    "archive.start": "Archive results",
    "history.title": "Archive history",
    "history.help": "Preview videos and final renders are listed separately.",
    "history.refresh": "Refresh",
    "history.loading": "Loading history...",
    "history.empty": "No archives",
    "history.legacy": "Legacy archive",
    "history.source_unavailable": "Source folder record unavailable",
    "history.counts": "{segments} segments · {jpegs} JPEGs",
    "history.recipe": "Recipe: {value}",
    "history.preview": "Preview",
    "history.output": "Final render",
    "history.missing": "{label}: none",
    "history.record_unavailable": "Record unavailable",
    "settings.title": "Settings",
    "settings.help": "Settings are saved only to local configuration.",
    "settings.directories": "Directories",
    "settings.workspace": "Workspace directory",
    "settings.output": "Output directory",
    "settings.archive": "Archive directory",
    "settings.pick": "Choose",
    "settings.processing": "Processing",
    "settings.default_recipe": "Default recipe",
    "settings.gap": "Automatic segment gap (seconds)",
    "settings.preview": "Preview",
    "settings.preview_fps": "Preview frame rate",
    "settings.preview_width": "Preview width",
    "settings.export": "Export",
    "settings.save": "Save settings",
    "settings.saved": "Saved",
    "settings.saved_restart": "Saved; restart the application to apply",
    "task.bar": "Task status bar",
    "task.start": "Start processing",
    "task.retry_stage": "Retry stage",
    "task.retry_render": "Render again",
    "task.retry_analyze": "Analyze and render again",
    "task.retry": "Retry",
    "task.cancel": "Cancel",
    "task.progress": "Task progress",
    "task.waiting": "Waiting for a task",
    "task.logs": "Task log",
    "task.no_logs": "No log entries",
    "status.idle": "Idle",
    "status.pending": "Pending",
    "status.analyzed": "Analyzed",
    "status.rendered": "Rendered",
    "status.queued": "Queued",
    "status.running": "Processing",
    "status.completed": "Completed",
    "status.failed": "Failed",
    "status.cancelling": "Cancelling",
    "status.cancelled": "Cancelled",
    "status.interrupted": "Interrupted",
    "status.unknown": "Unknown",
    "dialog.archive.title": "Confirm archive",
    "dialog.archive.body": "Archive validates and stores current JPEGs, previews, and final videos, then clears the workspace. External source photos are always preserved.",
    "dialog.archive.confirm": "Archive",
    "dialog.clear.title": "Clear current project",
    "dialog.clear.body": "This clears project state and processing results from the workspace. External source photos are not deleted.",
    "dialog.clear.confirm": "Clear project",
    "dialog.cancel": "Cancel",
    "error.dismiss": "Dismiss error",
    "error.invalid_media_path": "The source directory is invalid or outside the allowed location.",
    "error.native_picker_unavailable": "The native directory picker is unavailable in this runtime mode.",
    "error.runtime_unavailable": "Runtime directories are unavailable. Check mounts and permissions.",
    "error.task_busy": "Another task is already running.",
    "error.not_found": "The requested resource does not exist.",
    "error.internal_error": "The server could not complete the request.",
    "error.unknown": "The operation failed."
  };

  const TRANSLATIONS = { "zh-CN": zh, en };

  function normalizeTheme(value) {
    return SUPPORTED_THEMES.includes(value) ? value : "system";
  }

  function normalizeLanguage(value, browserLanguage = "en") {
    if (SUPPORTED_LANGUAGES.includes(value)) return value;
    return String(browserLanguage).toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  }

  function t(language, key, params = {}) {
    const template = TRANSLATIONS[language]?.[key] ?? zh[key];
    if (template === undefined) {
      if (typeof console !== "undefined") console.warn(`Missing translation: ${key}`);
      return key;
    }
    return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
  }

  function loadPreferences(storage, browserLanguage) {
    return {
      theme: normalizeTheme(storage?.getItem("solis.theme")),
      language: normalizeLanguage(storage?.getItem("solis.language"), browserLanguage),
    };
  }

  function applyPreferences(documentRef, preferences) {
    documentRef.documentElement.dataset.theme = normalizeTheme(preferences.theme);
    documentRef.documentElement.lang = normalizeLanguage(preferences.language, preferences.language);
  }

  return {
    SUPPORTED_THEMES,
    SUPPORTED_LANGUAGES,
    TRANSLATIONS,
    normalizeTheme,
    normalizeLanguage,
    t,
    loadPreferences,
    applyPreferences,
  };
});
