"use strict";

(function initSolisUI(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.SolisUI = api;

  if (root?.document) {
    const preferences = api.loadPreferences(root.localStorage, root.navigator?.language);
    api.applyPreferences(root.document, preferences);
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function buildSolisUI() {
  const SUPPORTED_THEMES = ["light", "dark", "system"];
  const SUPPORTED_LANGUAGES = ["zh-CN", "en"];

  const zh = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse 延时摄影工作台",
    "nav.primary": "主导航",
    "nav.workbench": "工作台",
    "nav.history": "处理历史与日志",
    "nav.logs": "日志",
    "nav.recipes": "色彩配方",
    "nav.settings": "设置",
    "theme.label": "主题",
    "theme.light": "白天",
    "theme.dark": "夜间",
    "theme.system": "跟随系统",
    "language.label": "语言",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "尚未选择素材目录",
    "source.title": "素材",
    "source.help": "选择包含 ARW、JPG 或 JPEG 的目录。",
    "source.summary": "{frames} 帧，{segments} 个分段，拍摄时长 {duration}",
    "source.duration": "{minutes} 分 {seconds} 秒",
    "source.pick": "选择目录",
    "source.scan": "扫描素材",
    "source.clear": "清除当前项目",
    "source.external_safe": "外部源照片始终保留",
    "segment.title": "分段",
    "segment.count": "{count} 段",
    "segment.empty": "扫描后在此审核分段",
    "segment.unnamed": "未命名分段",
    "segment.focal_unknown": "焦距未知",
    "segment.time_unknown": "时间未知",
    "segment.meta": "{count} 帧 · {focal} · {time}",
    "segment.list": "分段列表",
    "segment.reorder": "调整分段顺序",
    "segment.move_up": "上移分段",
    "segment.move_down": "下移分段",
    "segment.multi_select": "多选",
    "segment.merge_select": "选择要合并分段",
    "segment.split_frame": "拆分帧",
    "segment.split": "拆分",
    "segment.merge": "合并",
    "segment.current": "当前分段",
    "segment.select": "选择一个分段",
    "segment.none": "未选择",
    "segment.frames": "{count} 帧 · {duration}",
    "segment.frames_only": "{count} 帧",
    "segment.duration": "{seconds} 秒",
    "preview.none": "暂无预览",
    "preview.select": "选择分段后查看代表帧",
    "preview.current": "当前分段预览",
    "preview.histogram": "直方图",
    "preview.histogram_aria": "当前画面 RGB 直方图",
    "preview.alt": "{name}代表帧",
    "preview.representative": "当前代表帧",
    "preview.waiting": "正在等待缩略图",
    "chart.title": "视频图表",
    "chart.type_label": "图表类型",
    "chart.type.brightness": "亮度趋势",
    "chart.type.gain": "曝光增益",
    "chart.type.change": "帧间变化",
    "chart.legend.brightness": "原始 / 目标",
    "chart.legend.gain": "增益（1.0 = 不调整）",
    "chart.legend.change": "相邻帧亮度差",
    "chart.aria": "视频逐帧分析图表",
    "chart.empty": "分析后显示曲线",
    "recipe.title": "色彩配方",
    "recipe.mode": "配方预设",
    "recipe.natural": "自然",
    "recipe.clear": "通透",
    "recipe.punchy": "色彩强化",
    "recipe.custom": "自定义",
    "recipe.strength": "配方强度",
    "recipe.golden": "日照金山强度",
    "recipe.deflicker": "启用去闪",
    "recipe.advanced": "高级参数",
    "recipe.window": "去闪窗口",
    "recipe.gain_limit": "曝光增益上限",
    "recipe.golden_start": "强化起始帧",
    "recipe.golden_end": "强化结束帧",
    "frames.title": "帧检查",
    "frames.multi_select": "多选",
    "frames.none_selected": "未选择帧",
    "frames.selected": "已选择 {count} 帧",
    "frames.selected_range": "已选 {count} 帧：{start}–{end}",
    "frames.empty": "该分段暂无缩略图",
    "frames.select_segment": "选择分段后检查帧",
    "frames.strip": "分段缩略图带",
    "frames.previous": "上一页缩略图",
    "frames.next": "下一页缩略图",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "标记坏帧",
    "frames.unmark_bad": "取消坏帧",
    "frames.set_golden_start": "设为强化起点",
    "frames.set_golden_end": "设为强化终点",
    "frames.bad": "坏帧",
    "frames.index": "第 {index} 帧",
    "frames.shutter": "快门 {value}",
    "frames.luminance": "亮度 {value}",
    "export.title": "最终导出",
    "export.help": "渲染、导出、预览和归档仅作用于当前分段。",
    "export.fps": "帧率",
    "export.resolution": "分辨率",
    "export.codec": "编码",
    "export.crf": "CRF",
    "export.source_width": "原图宽度",
    "export.start": "导出视频",
    "export.preview": "预览视频",
    "archive.start": "归档成果",
    "archive.explain": "校验并保存成果副本到归档目录",
    "history.title": "处理历史与日志",
    "history.help": "查看归档成果和当前服务的处理日志。",
    "history.archive_heading": "归档记录",
    "history.refresh": "刷新",
    "history.loading": "正在读取历史...",
    "history.empty": "暂无归档",
    "history.legacy": "旧版归档",
    "history.source_unavailable": "源目录记录不可用",
    "history.counts": "{segments} 段 · {jpegs} 张 JPEG",
    "history.recipe": "配方：{value}",
    "history.preview": "预览",
    "history.output": "最终成片",
    "history.missing": "{label}：无",
    "history.record_unavailable": "记录不可用",
    "settings.title": "设置",
    "settings.help": "设置只保存到本机配置。",
    "settings.directories": "目录",
    "settings.workspace": "工作目录",
    "settings.output": "输出目录",
    "settings.archive": "归档目录",
    "settings.pick": "选择",
    "settings.processing": "处理",
    "settings.default_recipe": "默认配方",
    "settings.gap": "自动分段时间间隔（秒）",
    "settings.log_level": "日志级别",
    "settings.logging": "DEBUG 会记录逐帧进度、处理参数和异常堆栈。",
    "settings.preview": "预览",
    "settings.preview_fps": "预览帧率",
    "settings.preview_width": "预览宽度",
    "settings.export": "导出",
    "settings.save": "保存设置",
    "settings.saved": "已保存",
    "settings.saved_restart": "已保存，重启程序后生效",
    "logs.title": "任务日志",
    "logs.help": "显示当前服务运行期间的任务记录，命令行窗口会同步输出。",
    "logs.clear": "清除历史日志",
    "presets.title": "色彩配方",
    "presets.help": "管理实际参与渲染的饱和度、对比度和明暗枢轴参数。",
    "presets.list": "色彩配方列表",
    "presets.editor": "配方参数",
    "presets.new": "新建配方",
    "presets.new_badge": "新配方",
    "presets.name": "名称",
    "presets.saturation": "饱和度",
    "presets.contrast": "对比度",
    "presets.pivot": "明暗枢轴",
    "presets.builtin": "内置",
    "presets.user": "自定义",
    "presets.unnamed": "未命名配方",
    "presets.save": "保存预设",
    "presets.delete": "删除预设",
    "presets.saved": "配方已保存",
    "presets.deleted": "配方已删除",
    "presets.delete_confirm": "确认删除配方“{name}”？",
    "task.bar": "任务状态栏",
    "task.current_panel": "当前分段任务",
    "task.start": "开始处理",
    "task.start_current": "渲染",
    "task.cancel": "取消",
    "task.progress": "任务进度",
    "task.waiting": "等待任务",
    "task.logs": "任务日志",
    "task.no_logs": "暂无日志",
    "status.idle": "空闲",
    "status.pending": "待处理",
    "status.analyzed": "已分析",
    "status.rendered": "已渲染",
    "status.queued": "排队中",
    "status.running": "处理中",
    "status.completed": "已完成",
    "status.failed": "失败",
    "status.cancelling": "正在取消",
    "status.cancelled": "已取消",
    "status.interrupted": "已中断",
    "status.unknown": "未知",
    "dialog.archive.title": "确认归档当前分段",
    "dialog.archive.body": "将归档当前分段：{name}\n归档只复制当前分段及其 MP4，不会清理当前项目、源照片或输出视频。",
    "dialog.archive.confirm": "确认归档",
    "dialog.export_progress.title": "正在导出视频",
    "dialog.export_progress.preparing": "正在准备当前分段，请稍候。",
    "dialog.export_progress.running": "视频导出中：{percent}%",
    "dialog.export_progress.cancelling": "正在取消导出",
    "dialog.export_progress.cancel": "取消导出",
    "dialog.export_progress.cancelled": "视频导出已取消",
    "dialog.export_progress.cancelled_body": "未完成的导出任务已停止。",
    "dialog.export_progress.failed": "视频导出失败",
    "dialog.export_progress.aria": "视频导出进度",
    "dialog.export_done.title": "视频导出完成",
    "dialog.export_done.body": "导出目录：{path}\n文件：{files}",
    "dialog.archive_done.title": "成果归档完成",
    "dialog.archive_done.body": "归档目录：{path}\n当前分段已归档，当前项目和工作区保持不变。",
    "dialog.result.history": "查看历史归档",
    "dialog.result.ok": "确定",
    "dialog.clear.title": "清除当前项目",
    "dialog.clear.body": "只清除工作区中的当前项目状态和处理结果。源照片、输出视频和归档目录均不会删除，也不会自动归档。",
    "dialog.clear.confirm": "确认清除",
    "dialog.cancel": "取消",
    "browser.title": "选择素材目录",
    "browser.breadcrumb": "素材目录路径",
    "browser.root": "根目录",
    "browser.empty": "当前目录没有子目录",
    "browser.choose": "选择当前目录",
    "error.dismiss": "关闭错误提示",
    "error.invalid_media_path": "素材目录无效或超出允许范围。",
    "error.native_picker_unavailable": "当前运行模式不支持本机目录选择器。",
    "error.runtime_unavailable": "运行目录不可用，请检查挂载和权限。",
    "error.task_busy": "已有任务正在运行。",
    "error.invalid_color_preset": "色彩配方参数无效。",
    "error.preset_builtin": "内置色彩配方不能删除。",
    "error.preset_in_use": "该色彩配方正在使用，不能删除。",
    "error.preset_not_found": "色彩配方不存在。",
    "error.not_found": "请求的资源不存在。",
    "error.internal_error": "服务器处理请求时失败。",
    "error.unknown": "操作失败。"
  };

  const en = {
    "app.name": "Solis_Timelapse",
    "app.title": "Solis_Timelapse Workbench",
    "nav.primary": "Primary navigation",
    "nav.workbench": "Workbench",
    "nav.history": "History & logs",
    "nav.logs": "Logs",
    "nav.recipes": "Color recipes",
    "nav.settings": "Settings",
    "theme.label": "Theme",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.system": "System",
    "language.label": "Language",
    "language.zh-CN": "中文",
    "language.en": "English",
    "source.none": "No source folder selected",
    "source.title": "Source",
    "source.help": "Choose a folder containing ARW, JPG, or JPEG files.",
    "source.summary": "{frames} frames, {segments} segments, capture duration {duration}",
    "source.duration": "{minutes} min {seconds} sec",
    "source.pick": "Choose folder",
    "source.scan": "Scan source",
    "source.clear": "Clear project",
    "source.external_safe": "External source photos are always preserved",
    "segment.title": "Segments",
    "segment.count": "{count} segments",
    "segment.empty": "Scan a source to review its segments here",
    "segment.unnamed": "Unnamed segment",
    "segment.focal_unknown": "Focal length unknown",
    "segment.time_unknown": "Time unknown",
    "segment.meta": "{count} frames · {focal} · {time}",
    "segment.list": "Segment list",
    "segment.reorder": "Reorder segments",
    "segment.move_up": "Move segment up",
    "segment.move_down": "Move segment down",
    "segment.multi_select": "Multi-select",
    "segment.merge_select": "Select segments to merge",
    "segment.split_frame": "Split frame",
    "segment.split": "Split",
    "segment.merge": "Merge",
    "segment.current": "Current segment",
    "segment.select": "Select a segment",
    "segment.none": "Not selected",
    "segment.frames": "{count} frames · {duration}",
    "segment.frames_only": "{count} frames",
    "segment.duration": "{seconds} sec",
    "preview.none": "No preview",
    "preview.select": "Select a segment to view its representative frame",
    "preview.current": "Current segment preview",
    "preview.histogram": "Histogram",
    "preview.histogram_aria": "Current image RGB histogram",
    "preview.alt": "Representative frame for {name}",
    "preview.representative": "Current representative frame",
    "preview.waiting": "Waiting for thumbnails",
    "chart.title": "Video charts",
    "chart.type_label": "Chart type",
    "chart.type.brightness": "Brightness trend",
    "chart.type.gain": "Exposure gain",
    "chart.type.change": "Frame change",
    "chart.legend.brightness": "Original / Target",
    "chart.legend.gain": "Gain (1.0 = unchanged)",
    "chart.legend.change": "Brightness difference between adjacent frames",
    "chart.aria": "Per-frame video analysis chart",
    "chart.empty": "Run analysis to display curves",
    "recipe.title": "Color recipe",
    "recipe.mode": "Recipe preset",
    "recipe.natural": "Natural",
    "recipe.clear": "Clear",
    "recipe.punchy": "Color boost",
    "recipe.custom": "Custom",
    "recipe.strength": "Recipe strength",
    "recipe.golden": "Golden mountain strength",
    "recipe.deflicker": "Enable deflicker",
    "recipe.advanced": "Advanced parameters",
    "recipe.window": "Deflicker window",
    "recipe.gain_limit": "Exposure gain limit",
    "recipe.golden_start": "Boost start frame",
    "recipe.golden_end": "Boost end frame",
    "frames.title": "Frame review",
    "frames.multi_select": "Multi-select",
    "frames.none_selected": "No frames selected",
    "frames.selected": "{count} frames selected",
    "frames.selected_range": "{count} frames selected: {start}–{end}",
    "frames.empty": "No thumbnails for this segment",
    "frames.select_segment": "Select a segment to review frames",
    "frames.strip": "Segment thumbnail strip",
    "frames.previous": "Previous thumbnail page",
    "frames.next": "Next thumbnail page",
    "frames.page": "{current} / {total}",
    "frames.mark_bad": "Mark bad frame",
    "frames.unmark_bad": "Unmark bad frame",
    "frames.set_golden_start": "Set boost start",
    "frames.set_golden_end": "Set boost end",
    "frames.bad": "Bad frame",
    "frames.index": "Frame {index}",
    "frames.shutter": "Shutter {value}",
    "frames.luminance": "Brightness {value}",
    "export.title": "Final export",
    "export.help": "Render, export, preview, and archive apply only to the current segment.",
    "export.fps": "Frame rate",
    "export.resolution": "Resolution",
    "export.codec": "Codec",
    "export.crf": "CRF",
    "export.source_width": "Source width",
    "export.start": "Export video",
    "export.preview": "Preview video",
    "archive.start": "Archive results",
    "archive.explain": "Validate and copy results to the archive directory",
    "history.title": "History & logs",
    "history.help": "Review archived results and processing logs from the current service.",
    "history.archive_heading": "Archive records",
    "history.refresh": "Refresh",
    "history.loading": "Loading history...",
    "history.empty": "No archives",
    "history.legacy": "Legacy archive",
    "history.source_unavailable": "Source folder record unavailable",
    "history.counts": "{segments} segments · {jpegs} JPEGs",
    "history.recipe": "Recipe: {value}",
    "history.preview": "Preview",
    "history.output": "Final render",
    "history.missing": "{label}: none",
    "history.record_unavailable": "Record unavailable",
    "settings.title": "Settings",
    "settings.help": "Settings are saved only to local configuration.",
    "settings.directories": "Directories",
    "settings.workspace": "Workspace directory",
    "settings.output": "Output directory",
    "settings.archive": "Archive directory",
    "settings.pick": "Choose",
    "settings.processing": "Processing",
    "settings.default_recipe": "Default recipe",
    "settings.gap": "Automatic segment gap (seconds)",
    "settings.log_level": "Log level",
    "settings.logging": "DEBUG records per-frame progress, processing parameters, and exception tracebacks.",
    "settings.preview": "Preview",
    "settings.preview_fps": "Preview frame rate",
    "settings.preview_width": "Preview width",
    "settings.export": "Export",
    "settings.save": "Save settings",
    "settings.saved": "Saved",
    "settings.saved_restart": "Saved; restart the application to apply",
    "logs.title": "Task logs",
    "logs.help": "Task history for this service session. The command window shows the same events.",
    "logs.clear": "Clear log history",
    "presets.title": "Color recipes",
    "presets.help": "Manage the saturation, contrast, and tonal pivot used during rendering.",
    "presets.list": "Color recipe list",
    "presets.editor": "Recipe parameters",
    "presets.new": "New recipe",
    "presets.new_badge": "New recipe",
    "presets.name": "Name",
    "presets.saturation": "Saturation",
    "presets.contrast": "Contrast",
    "presets.pivot": "Tonal pivot",
    "presets.builtin": "Built in",
    "presets.user": "Custom",
    "presets.unnamed": "Untitled recipe",
    "presets.save": "Save preset",
    "presets.delete": "Delete preset",
    "presets.saved": "Recipe saved",
    "presets.deleted": "Recipe deleted",
    "presets.delete_confirm": "Delete recipe “{name}”?",
    "task.bar": "Task status bar",
    "task.current_panel": "Current segment task",
    "task.start": "Start processing",
    "task.start_current": "Render",
    "task.cancel": "Cancel",
    "task.progress": "Task progress",
    "task.waiting": "Waiting for a task",
    "task.logs": "Task log",
    "task.no_logs": "No log entries",
    "status.idle": "Idle",
    "status.pending": "Pending",
    "status.analyzed": "Analyzed",
    "status.rendered": "Rendered",
    "status.queued": "Queued",
    "status.running": "Processing",
    "status.completed": "Completed",
    "status.failed": "Failed",
    "status.cancelling": "Cancelling",
    "status.cancelled": "Cancelled",
    "status.interrupted": "Interrupted",
    "status.unknown": "Unknown",
    "dialog.archive.title": "Archive current segment",
    "dialog.archive.body": "Archive current segment: {name}\nOnly the current segment and its MP4 file are copied. The current project, source photos, and output videos remain unchanged.",
    "dialog.archive.confirm": "Archive",
    "dialog.export_progress.title": "Exporting video",
    "dialog.export_progress.preparing": "Preparing the current segment.",
    "dialog.export_progress.running": "Exporting video: {percent}%",
    "dialog.export_progress.cancelling": "Cancelling export",
    "dialog.export_progress.cancel": "Cancel export",
    "dialog.export_progress.cancelled": "Video export cancelled",
    "dialog.export_progress.cancelled_body": "The unfinished export task has stopped.",
    "dialog.export_progress.failed": "Video export failed",
    "dialog.export_progress.aria": "Video export progress",
    "dialog.export_done.title": "Video export complete",
    "dialog.export_done.body": "Output directory: {path}\nFiles: {files}",
    "dialog.archive_done.title": "Archive complete",
    "dialog.archive_done.body": "Archive directory: {path}\nThe current segment was archived. The current project and workspace remain unchanged.",
    "dialog.result.history": "View archive history",
    "dialog.result.ok": "OK",
    "dialog.clear.title": "Clear current project",
    "dialog.clear.body": "This only clears the current project state and processing results from the workspace. Source photos, output videos, and archives are preserved. No archive is created automatically.",
    "dialog.clear.confirm": "Clear project",
    "dialog.cancel": "Cancel",
    "browser.title": "Choose source directory",
    "browser.breadcrumb": "Source directory path",
    "browser.root": "Root",
    "browser.empty": "This directory has no subdirectories",
    "browser.choose": "Choose current directory",
    "error.dismiss": "Dismiss error",
    "error.invalid_media_path": "The source directory is invalid or outside the allowed location.",
    "error.native_picker_unavailable": "The native directory picker is unavailable in this runtime mode.",
    "error.runtime_unavailable": "Runtime directories are unavailable. Check mounts and permissions.",
    "error.task_busy": "Another task is already running.",
    "error.invalid_color_preset": "The color recipe parameters are invalid.",
    "error.preset_builtin": "Built-in color recipes cannot be deleted.",
    "error.preset_in_use": "This color recipe is in use and cannot be deleted.",
    "error.preset_not_found": "The color recipe does not exist.",
    "error.not_found": "The requested resource does not exist.",
    "error.internal_error": "The server could not complete the request.",
    "error.unknown": "The operation failed."
  };

  const TRANSLATIONS = { "zh-CN": zh, en };

  function normalizeTheme(value) {
    return SUPPORTED_THEMES.includes(value) ? value : "system";
  }

  function normalizeLanguage(value, browserLanguage = "en") {
    if (SUPPORTED_LANGUAGES.includes(value)) return value;
    return String(browserLanguage).toLowerCase().startsWith("zh") ? "zh-CN" : "en";
  }

  function t(language, key, params = {}) {
    const template = TRANSLATIONS[language]?.[key] ?? zh[key];
    if (template === undefined) {
      if (typeof console !== "undefined") console.warn(`Missing translation: ${key}`);
      return key;
    }
    return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
  }

  function loadPreferences(storage, browserLanguage) {
    return {
      theme: normalizeTheme(storage?.getItem("solis.theme")),
      language: normalizeLanguage(storage?.getItem("solis.language"), browserLanguage),
    };
  }

  function applyPreferences(documentRef, preferences) {
    documentRef.documentElement.dataset.theme = normalizeTheme(preferences.theme);
    documentRef.documentElement.lang = normalizeLanguage(preferences.language, preferences.language);
  }

  return {
    SUPPORTED_THEMES,
    SUPPORTED_LANGUAGES,
    TRANSLATIONS,
    normalizeTheme,
    normalizeLanguage,
    t,
    loadPreferences,
    applyPreferences,
  };
});
